version: '3.8'

services:
  dbProduct:
    image: postgres:13
    container_name: product_db_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: onlineshop-product
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  pgAdmin:
    image: elestio/pgadmin
    container_name: product_pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 9090
    ports:
      - "9090:9090"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  my-network: {}