version: '3.8'

services:
  product:
    image: productimage
    container_name: product_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbProduct:5432/onlineshop-product
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - dbProduct
    networks:
      - my-network

  dbProduct:
    image: postgres:13
    container_name: product_db_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: onlineshop-product
    ports:
      - "8081:5432"
    volumes:
      - postgres_data_product:/var/lib/postgresql/data
    networks:
      - my-network

  pgAdmin:
    image: elestio/pgadmin
    container_name: product_pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 9090
    ports:
      - "8082:9090"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my-network

volumes:
  postgres_data_product:
  pgadmin_data:

networks:
  my-network: {}